.gitignore, custom_components/mammotion/__init__.py, custom_components/mammotion/lawn_mower.py, custom_components/mammotion/manifest.json, custom_components/mammotion/sensor.py, pyproject.toml
Added a few sensors as a starting point
=> Added Luba sensor data pt1

custom_components/mammotion/__init__.py, custom_components/mammotion/config_flow.py, custom_components/mammotion/coordinator.py, custom_components/mammotion/entity.py
- removed discovery title by mistake
- ruff
=> Re-add discovery title

custom_components/mammotion/const.py, custom_components/mammotion/coordinator.py, custom_components/mammotion/lawn_mower.py, custom_components/mammotion/sensor.py, custom_components/mammotion/translations/en.json
- exception handling
- mypy: two missing returns
=> Add exception handling for commands

custom_components/mammotion/translations/fr.json
Hi 👋
I added french translation 🇫🇷
=> Added French translation

custom_components/mammotion/translations/it.json
I translated the menu texts into my language.
=> Added Italian translation

custom_components/mammotion/translations/ro.json
add translation to Romanian language
___
- Introduced a comprehensive Romanian translation for the Mammotion component.
- Translations cover configuration messages, sensor states, and device actions.
- Aims to improve accessibility for Romanian users.
___
<tr>
<td>
<details>
<summary><strong>ro.json</strong><dd><code>Add Romanian Translations for Mammotion Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/translations/ro.json
<li>Added Romanian translations for configuration and entity settings.<br> <li> Included translations for various device states and actions.<br> <li> Enhanced …
=> Add Romanian Language Support for Mammotion

custom_components/mammotion/translations/cs.json
translation to czech
___
- Introduced a new `cs.json` file containing complete Czech translations for the Mammotion mower.
- Translations cover configuration messages, sensor names, button actions, and error messages.
- Aimed at improving accessibility for Czech-speaking users of the application.
___
<tr>
<td>
<details>
<summary><strong>cs.json</strong><dd><code>Add Czech Translations for Mammotion Mower</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added Czech language translations for the Mammotion mower …
=> Add Czech Language Support for Mammotion Mower

custom_components/mammotion/translations/cs.json, custom_components/mammotion/translations/en.json, custom_components/mammotion/translations/fr.json, custom_components/mammotion/translations/it.json, custom_components/mammotion/translations/nl.json, custom_components/mammotion/translations/ro.json
- Introduced new language support for Czech, Dutch, and Romanian.
- Cleaned up existing translation files by removing unnecessary descriptions.
- Enhanced user experience through localized interfaces.
___
<tr>
<td>
<details>
<summary><strong>cs.json</strong><dd><code>Add Czech Language Support for Mammotion</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added Czech translations for various configuration and entity labels.<br> <li> Included error messages and descriptions for user interactions.<br> <li> …
=> Add Multi-Language Support for Mammotion

custom_components/mammotion/translations/de.json
Created a new JSON file "de.json" with German translation for the Mammotion - Home Assistant Integration. Thanks to [mikey0000](https://github.com/mikey0000) for this great integration!
There were a few variables where i wasn't sure if the translation fits 100percent, but from my point of view this translation file is a very good start for German-speaking users
___
- Introduced `de.json` for German translations in the Mammotion Home Assistant integration.
- Translations cover various aspects including configuration messages, sensor names, and error messages.
- Aimed at improving accessibility for German-speaking users.
___
<tr>
<td>
<details> …
=> Add German Language Support for Mammotion-HA

custom_components/mammotion/translations/fr.json
- Added new translations to improve user experience in French.
- Included prompts for device name, Wi-Fi usage, and account credentials.
- Enhanced configuration options for better usability.
___
<tr>
<td>
<details>
<summary><strong>fr.json</strong><dd><code>Enhanced French Translations for Device Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/translations/fr.json
<li>Added new French translations for device configuration.<br> <li> Enhanced user prompts for reconfiguration and device naming.<br> <li> Included additional options for Bluetooth connectivity.<br>
</details>
</td>
<td><a …
=> Enhanced French Translations and Configuration Options

custom_components/mammotion/translations/de.json
- Added new German translations for device configuration variables.
- Enhanced the user flow with additional data fields for better clarity.
- Improved existing translations to ensure consistency.
___
<tr>
<td>
<details>
<summary><strong>de.json</strong><dd><code>Update German translations with new variables and options</code></dd></summary>
<hr>
<li>Added German translations for new variables.<br> <li> Updated existing translations for clarity.<br> <li> Enhanced configuration options with new data fields.<br>
</details>
</td>
<td><a href="https://github.com/mikey0000/Mammotion-HA/pull/86/files#diff-c28a07b …
=> Enhance German translations for Mammotion configuration variables

custom_components/mammotion/translations/nl.json
JSON was dumping... (Invalid, missing commas)
___
- Fixed JSON syntax errors by adding missing commas.
- Ensured the nl.json file is valid for proper translation handling.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting
<tr>
<td>
<details>
<summary><strong>nl.json</strong><dd><code>Fix JSON formatting issues in nl.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/translations/nl.json
<li>Added missing commas to fix JSON formatting.<br> <li> Corrected syntax errors to ensure valid JSON structure.<br>
</details>
</td>
<td><a …
=> Fix JSON Formatting Issues in nl.json

info.md
Checked Wi-Fi support to match information in README.md as it's currently not showing Wi-Fi support in HACS info.
___
- Updated the roadmap to indicate that Wi-Fi support is now checked.
- Ensures that the documentation accurately reflects the integration's capabilities.
___
<tr>
<td>
<details>
<summary><strong>info.md</strong><dd><code>Update Wi-Fi Support Status in Roadmap</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
info.md
<li>Updated the Wi-Fi support status to checked in the roadmap.<br> <li> Reflects the current capabilities of the …
=> Update Wi-Fi Support Status in Documentation

custom_components/mammotion/translations/cs.json
- Enhanced the Czech translation file with additional configuration options and button actions.
- Improved user interface text for better understanding and usability.
___
<tr>
<td>
<details>
<summary><strong>cs.json</strong><dd><code>Enhance Czech Translations with New Options and Actions</code>&nbsp; &nbsp; </dd></summary>
<hr>
<li>Added new configuration options for the application.<br> <li> Introduced new button actions for emergency nudges.<br> <li> Updated titles and descriptions for better clarity.<br>
</details>
</td>
<td><a href="https://github.com/mikey0000/Mammotion-HA/pull/101/files#diff-a4dc9af1 …
=> Enhance Czech Translations in cs.json

custom_components/mammotion/translations/de.json
- Enhanced the German translations by adding new terms for various functionalities.
- Corrected existing translations to improve accuracy and clarity.
- Ensured a more comprehensive localization experience for German-speaking users.
___
<tr>
<td>
<details>
<summary><strong>de.json</strong><dd><code>Update German translations with new entries and corrections</code></dd></summary>
<hr>
<li>Added new translations for various commands and modes.<br> <li> Corrected existing translations for better clarity.<br> <li> Improved the overall localization of the application.<br>
</details>
</td>
<td><a …
=> Update German translations with new terms and corrections

custom_components/mammotion/manifest.json, custom_components/mammotion/translations/ro.json
update to 0.1.21
___
- Enhanced the Romanian translations for the Mammotion component by adding new configuration options and entity attributes.
- Introduced emergency nudge actions for better user control.
- Updated cutting mode options to include more states for improved functionality.
___
<tr>
<td>
<details>
<summary><strong>ro.json</strong><dd><code>Enhance Romanian Translations for Mammotion Component</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/translations/ro.json
<li>Added new configuration options for the Mammotion component.<br> <li> Introduced new entity attributes for enhanced functionality.<br> <li> …
=> Enhance Romanian Translations in ro.json for Mammotion Component

custom_components/mammotion/translations/cs.json
update to 0.1.21
___
- Enhanced Czech translations in `cs.json` for better user experience.
- Added translations for Bluetooth connection status and cutting mode states.
- Improved naming for device tracking.
___
<tr>
<td>
<details>
<summary><strong>cs.json</strong><dd><code>Update Czech translations for Mammotion component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added new translation for Bluetooth connection status.<br> <li> Introduced new cutting mode states in the translation.<br> <li> Enhanced device tracker name translation.<br>
</details>
</td>
<td><a …
=> Enhance Czech Translations in cs.json for Mammotion

custom_components/mammotion/translations/de.json
- Enhanced the German translation file with new terms for better user experience.
- Added a description for maintaining Bluetooth connection.
- Updated the cutting mode terminology and introduced additional grid options.
- Included a new term for the cutting angle.
___
<tr>
<td>
<details>
<summary><strong>de.json</strong><dd><code>Update German translations with new terms and options</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added new translation terms for Bluetooth connection maintenance.<br> <li> Updated the cutting mode name and added states for grid options.<br> <li> Introduced a new …
=> Update de.json for new terms and options

custom_components/mammotion/translations/cs.json
There's parse error in the json. Other changes so just to fix indetation.
=> Enhance Czech Translation Formatting and Completeness

custom_components/mammotion/translations/de.json
- Enhanced the German translation file by adding new terms and updating existing ones.
- Improved user experience by providing clearer and more concise translations.
- Ensured consistency in terminology across different features.
___
<tr>
<td>
<details>
<summary><strong>de.json</strong><dd><code>Update German translations with new and modified terms</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added new translation terms for Bluetooth connection and task <br>cancellation.<br> <li> Updated existing terms for grass collection, edge cutting, rain <br>detection, and side LED.<br> <li> Introduced new …
=> Update de.json with new and modified translation terms

custom_components/mammotion/__init__.py, custom_components/mammotion/coordinator.py, custom_components/mammotion/manifest.json, custom_components/mammotion/select.py, custom_components/mammotion/translations/pl.json, poetry.lock, pyproject.toml
- Enhanced MQTT connection handling during login to improve reliability.
- Introduced error handling for cloud login failures to prevent crashes.
- Fixed state retention issues in select options for better user experience.
- Updated translations for German and Polish languages to include new terms.
- Bumped version to 0.1.31 and updated dependencies.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Enhance MQTT connection handling and data management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/__init__.py
<li>Added error handling for MQTT connection during login.<br> <li> Improved data …
=> Enhance MQTT handling, update translations, and fix bugs

custom_components/mammotion/translations/cs.json
- Enhanced the Czech language translations in `cs.json` to include new features.
- Added translations for `stay_connected_bluetooth`, `cancel_task`, and `clear_all_mapdata`.
- Introduced new modes like `bypass_mode` and `cutting_angle_mode` with relevant translations.
- Improved user interface by updating existing terms for clarity.
___
<tr>
<td>
<details>
<summary><strong>cs.json</strong><dd><code>Update Czech translations with new features and improvements</code></dd></summary>
<hr>
<li>Added new translations for Bluetooth connectivity and task management.<br> <li> Introduced additional modes and …
=> Enhance Czech Translations in cs.json with New Features

custom_components/mammotion/coordinator.py, custom_components/mammotion/lawn_mower.py, custom_components/mammotion/manifest.json, custom_components/mammotion/translations/cs.json, poetry.lock, pyproject.toml
- Enhanced data management by adding save and restore functionality for the device state.
- Improved command execution logic to handle various device modes and states.
- Updated Czech translations to include new features and improve user experience.
- Updated `pymammotion` dependency to the latest version for better compatibility.
___
<tr>
<td>
<details>
<summary><strong>coordinator.py</strong><dd><code>Enhance Coordinator with Data Management and Command Handling</code></dd></summary>
<hr>
custom_components/mammotion/coordinator.py
<li>Added data saving and restoring functionality.<br> <li> Improved command execution after state changes.<br> <li> …
=> Enhance Device Management and Translations in Mammotion Component

custom_components/mammotion/translations/de.json
- Introduced a new term `clear_all_mapdata` in the German translation for clearing all map and area data.
- Ensured consistency in the formatting of existing terms.
___
<tr>
<td>
<details>
<summary><strong>de.json</strong><dd><code>Update German translations for map data management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added a new term for clearing all map data.<br> <li> Updated existing terms for consistency.<br>
</details>
</td>
<td><a href="https://github.com/mikey0000/Mammotion-HA/pull/133/files#diff-c28a07b60e03ec21803499d6c521fe20f2952f6a14901a5e279b77f54cc5b5 …
=> Update de.json with new term for clearing all map data

custom_components/mammotion/__init__.py, custom_components/mammotion/coordinator.py, custom_components/mammotion/manifest.json, custom_components/mammotion/switch.py, custom_components/mammotion/translations/de.json, poetry.lock, pyproject.toml
- Refactored async setup and data restoration logic for improved performance.
- Enhanced data management for device state, fixing issues with save and restore functionality.
- Updated German translations to include new terms for clearing map data.
- Bumped project version and updated dependencies.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Refactor async setup and data restoration logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/__init__.py
<li>Removed unnecessary condition for async_config_entry_first_refresh.<br> <li> Ensured async_restore_data …
=> Enhance Mammotion integration with data management and translation updates

custom_components/mammotion/__init__.py, custom_components/mammotion/coordinator.py, custom_components/mammotion/lawn_mower.py, custom_components/mammotion/manifest.json, custom_components/mammotion/services.yaml, custom_components/mammotion/strings.json, custom_components/mammotion/switch.py, custom_components/mammotion/translations/en.json
- Introduced a new service `start_mow` to allow users to start mowing with customizable settings.
- Enhanced the `async_plan_route` method to accept operation settings for better route planning.
- Updated the `async_start_mowing` method to handle new parameters and improved error handling.
- Added validation schema for the new service in `services.yaml`.
- Updated localization files to include descriptions for the new service and its fields.
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Service Registration for Mowing Tasks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Add Mowing Service with Customizable Options

custom_components/mammotion/translations/de.json
- Enhanced device management by ensuring a device is always selected and improving error handling.
- Updated service configurations and translations for the `start_mow` service.
- Bumped version and updated dependencies in the project manifest.
___
<tr>
<td>
<details>
<summary><strong>coordinator.py</strong><dd><code>Enhance Device Management in Coordinator</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/coordinator.py
<li>Introduced <code>device_name</code> initialization to handle device name <br>assignment.<br> <li> Improved …
=> Enhance Device Management and Update Translations for Mowing Service

custom_components/mammotion/translations/fr.json
Hi 👋
I updated the french translation 😁
___
- Enhanced the French language support by updating and adding translations.
- Improved clarity in device configuration and operational messages.
- Ensured consistency in terminology across the translation file.
___
<tr>
<td>
<details>
<summary><strong>fr.json</strong><dd><code>Enhance French Translations in fr.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/translations/fr.json
<li>Improved French translations for various messages.<br> <li> Added new translation …
=> Improve French Translations for Mammotion Component

custom_components/mammotion/const.py, custom_components/mammotion/coordinator.py
- Improved handling of expired credentials by adding checks before attempting to reconnect.
- Fixed issues with session reloading when credentials have expired.
- Ensured proper synchronization of devices with cloud services.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>const.py</strong><dd><code>Update EXPIRED_CREDENTIAL_EXCEPTIONS to use tuple</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/const.py
- Changed `EXPIRED_CREDENTIAL_EXCEPTIONS` from a set to a tuple.
</details>
</td>
<td><a href="https://github.com/mikey0000/Mammotion-HA/pull/166/files#diff-066c2f75913346e3baf9cd21c5694958 …
=> Enhance cloud error handling and fix session reload issues

custom_components/mammotion/manifest.json, pyproject.toml
- Upgraded `pymammotion` dependency from version `0.2.58` to `0.2.59` in both `manifest.json` and `pyproject.toml`.
- Ensures compatibility with the latest features and fixes in `pymammotion`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies
<tr>
<td>
<details>
<summary><strong>manifest.json</strong><dd><code>Update pymammotion version in manifest</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/manifest.json
- Updated `pymammotion` version from `0.2.58` to `0.2.59`.
</details>
</td>
<td><a href="https://github.com/mikey0000/Mammotion-HA/pull/167/files#diff-a63b …
=> Upgrade pymammotion to version 0.2.59

custom_components/mammotion/icons.json
- Introduced a comprehensive set of new icons for improved user interface.
- Enhanced the `select` section with icons for channel mode, mowing laps, and obstacle laps.
- Updated the `number` section with icons for various settings including blade height and working speed.
___
<tr>
<td>
<details>
<summary><strong>icons.json</strong><dd><code>Expanded Icon Set for Mowing and Obstacle Modes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/icons.json
<li>Added new icons for various modes and states.<br> <li> Expanded the <code>select</code> and <code>number</code> sections with …
=> Even more icons

custom_components/mammotion/services.yaml, custom_components/mammotion/strings.json, custom_components/mammotion/translations/en.json
Add translations for select options in services using translation_key (https://developers.home-assistant.io/docs/internationalization/core/#selectors)
Also, I think if it can be better to use `string` instead of `number` for option value as it will easy to use in `yaml`. But that would be a breaking change.
I only focused this PR on translations.
___
- Introduced translation keys for various select options in the services.
- Updated the options format to use numeric values directly for easier integration.
- Enhanced localization by adding corresponding translations in `strings.json` and `translations/en.json`.
___
<tr>
<td>
<details> …
=> Add translations for select options in services

custom_components/mammotion/www/agora-client.js
Add multiple camera support (Yuka) and Switch camera function
___
- Introduced multiple camera support, allowing users to switch between cameras seamlessly.
- Added a 'switch camera' button that becomes visible when more than one camera is available.
- Implemented logic to remember the user's preferred camera across sessions.
- Improved UI with camera labels for better identification of active cameras.
___
<tr>
<td>
<details>
<summary><strong>agora-client.js</strong><dd><code>Enhance camera functionality with multiple support and switching</code></dd></summary>
<hr>
custom_components/mammotion/www/agora-client.js
<li>Added support for multiple cameras …
=> Add multiple camera support (Yuka) and Switch camera function

custom_components/mammotion/camera.py, custom_components/mammotion/www/agora-client.js
Add joystick function
___
- Introduced joystick functionality for controlling the mower's movement.
- Added service calls for moving forward, backward, left, and right with speed validation.
- Implemented a joystick UI with buttons for directional control and a disclaimer for safety.
- Enhanced the video streaming interface to support joystick interactions.
___
<tr>
<td>
<details>
<summary><strong>camera.py</strong><dd><code>Implement Joystick Movement Controls for Mower</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/mammotion/camera.py
<li>Added joystick control functions for …
=> Add joystick function
